### PR TITLE
Upgrade terraform-provider-digitalocean to v2.28.1

### LINKED ISSUE #414: Upgrade terraform-provider-digitalocean to v2.28.1
Release details: https://github.com/digitalocean/terraform-provider-digitalocean/releases/tag/v2.28.1

### PR DESCRIPTION
**Pull request by aq17**
-Upgrading terraform-provider-digitalocean from v2.28.0 to v2.28.1.
Fixes #414 
-Upgrading pulumi-terraform-bridge from v3.42.1 to v3.47.3.

### CODE REVIEW

**Comment by t0yv0** [comment]
Seems to have some lint issues.

**Comment by aq17** [comment]
> Details

The same `AssertNoError` is deprecated lint error 🤷🏼‍♀️

**Comment by aq17** [comment]
Looks like [failing test](https://github.com/pulumi/pulumi-digitalocean/actions/runs/5072237264/jobs/9109782344?pr=431) is valid, version 11 is no longer supported as of 5/22/2023 according to [digitalocean's release notes](https://docs.digitalocean.com/release-notes/postgresql/)

Updating from version 11 to 12, see if it fixes the tests

**Review by t0yv0 — APPROVED** [review]
Brilliant, thank you!

**Pull request merged**
